require("vim-options")
require("misc")
require("config.lazy")
-- vim.keymap.set("n", "<leader>td", function()
--   vim.diagnostic.enable(not vim.diagnostic.is_enabled())
-- end, { silent = true, noremap = false })
