#!/usr/bin/env bash
set -e

[[ -n $HYPRLAND_DEBUG_CONF ]] && exit 0
USAGE="\
Import environment variables 
Usage: $0 <command>
Commands:
   tmux         import to tmux server
   system       import to systemd and dbus user session
   help         print this help
"

_envs=(
	# display
	WAYLAND_DISPLAY
	DISPLAY
	# xdg
	USERNAME
	XDG_BACKEND
	XDG_CURRENT_DESKTOP
	XDG_SESSION_TYPE
	XDG_SESSION_ID
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SEAT
	XDG_VTNR
	# hyprland
	HYPRLAND_CMD
	HYPRLAND_INSTANCE_SIGNATURE
  HYPRCURSOR_THEME
  HYPRCURSOR_SIZE
	# misc
	XCURSOR_SIZE
  XCURSOR_THEME
	# toolkit
  SDL_VIDEODRIVER
  GDK_BACKEND
  CLUTTER_BACKEND
	QT_QPA_PLATFORM
	QT_QPA_PLATFORMTHEME
  QT_AUTO_SCREEN_SCALE_FACTOR
	QT_WAYLAND_DISABLE_WINDOWDECORATION
  # NVIDIA
  __GLX_VENDOR_LIBRARY_NAME
  LIBVA_DRIVER_NAME
  NVD_BACKEND
  # electron
  #ELECTRON_OZONE_PLATFORM_HINT
)

case "$1" in
system)
	dbus-update-activation-environment --systemd "${_envs[@]}"
	;;
tmux)
	for v in "${_envs[@]}"; do
		if [[ -n ${!v} ]]; then
			tmux setenv -g "$v" "${!v}"
		fi
	done
	;;
help)
	echo -n "$USAGE"
	exit 0
	;;
*)
	echo "operation required"
	echo "use \"$0 help\" to see usage help"
	exit 1
	;;
esac
